export const categories = [
  { name: "Business", value: "business" },
  { name: "Entertainment", value: "entertainment" },
  { name: "General", value: "general" },
  { name: "Health", value: "health" },
  { name: "Science", value: "science" },
  { name: "Sports", value: "sports" },
  { name: "Technology", value: "technology" }
]
export const languages = [
  { name: "Arabic", value: "ar" },
  { name: "German", value: "de" },
  { name: "English", value: "en" },
  { name: "Spanish", value: "es" },
  { name: "French", value: "fr" },
  { name: "Hebrew", value: "he" },
  { name: "Italian", value: "it" },
  { name: "Dutch", value: "nl" },
  { name: "Norwegian", value: "no" },
  { name: "Portuguese", value: "pt" },
  { name: "Russian", value: "ru" },
  { name: "Swedish", value: "sv" },
  { name: "Urdu", value: "ud" },
  { name: "Chinese", value: "zh" }
]
export const countries = [
  { name: "United Arab Emirates", value: "ae" },
  { name: "Argentina", value: "ar" },
  { name: "Austria", value: "at" },
  { name: "Australia", value: "au" },
  { name: "Belgium", value: "be" },
  { name: "Bulgaria", value: "bg" },
  { name: "Brazil", value: "br" },
  { name: "Canada", value: "ca" },
  { name: "Switzerland", value: "ch" },
  { name: "China", value: "cn" },
  { name: "Colombia", value: "co" },
  { name: "Cuba", value: "cu" },
  { name: "Czech Republic", value: "cz" },
  { name: "Germany", value: "de" },
  { name: "Egypt", value: "eg" },
  { name: "France", value: "fr" },
  { name: "United Kingdom", value: "gb" },
  { name: "Greece", value: "gr" },
  { name: "Hong Kong", value: "hk" },
  { name: "Hungary", value: "hu" },
  { name: "Indonesia", value: "id" },
  { name: "Ireland", value: "ie" },
  { name: "Israel", value: "il" },
  { name: "India", value: "in" },
  { name: "Italy", value: "it" },
  { name: "Japan", value: "jp" },
  { name: "South Korea", value: "kr" },
  { name: "Lithuania", value: "lt" },
  { name: "Latvia", value: "lv" },
  { name: "Morocco", value: "ma" },
  { name: "Mexico", value: "mx" },
  { name: "Malaysia", value: "my" },
  { name: "Nigeria", value: "ng" },
  { name: "Netherlands", value: "nl" },
  { name: "Norway", value: "no" },
  { name: "New Zealand", value: "nz" },
  { name: "Philippines", value: "ph" },
  { name: "Poland", value: "pl" },
  { name: "Portugal", value: "pt" },
  { name: "Romania", value: "ro" },
  { name: "Serbia", value: "rs" },
  { name: "Russia", value: "ru" },
  { name: "Saudi Arabia", value: "sa" },
  { name: "Sweden", value: "se" },
  { name: "Singapore", value: "sg" },
  { name: "Slovenia", value: "si" },
  { name: "Slovakia", value: "sk" },
  { name: "Thailand", value: "th" },
  { name: "Turkey", value: "tr" },
  { name: "Taiwan", value: "tw" },
  { name: "Ukraine", value: "ua" },
  { name: "United States", value: "us" },
  { name: "Venezuela", value: "ve" },
  { name: "South Africa", value: "za" }
]