// export const categories = [
//   { name: "Business", value: "business" },
//   { name: "Entertainment", value: "entertainment" },
//   { name: "General", value: "general" },
//   { name: "Health", value: "health" },
//   { name: "Science", value: "science" },
//   { name: "Sports", value: "sports" },
//   { name: "Technology", value: "technology" }
// ]


export const categories = [
  { name: "Business", value: "business" },
  { name: "Crime", value: "crime" },
  { name: "Domestic", value: "domestic" },
  { name: "Education", value: "education" },
  { name: "Entertainment", value: "entertainment" },
  { name: "Environment", value: "environment" },
  { name: "Food", value: "food" },
  { name: "Health", value: "health" },
  { name: "Lifestyle", value: "lifestyle" },
  { name: "Other", value: "other" },
  { name: "Politics", value: "politics" },
  { name: "Science", value: "science" },
  { name: "Sports", value: "sports" },
  { name: "Technology", value: "technology" },
  { name: "Top", value: "top" },
  { name: "Tourism", value: "tourism" },
  { name: "World", value: "world" }
];

export const languages = [
  { name: "Arabic", value: "ar" },
  { name: "German", value: "de" },
  { name: "English", value: "en" },
  { name: "Spanish", value: "es" },
  { name: "French", value: "fr" },
  { name: "Hebrew", value: "he" },
  { name: "Italian", value: "it" },
  { name: "Dutch", value: "nl" },
  { name: "Norwegian", value: "no" },
  { name: "Portuguese", value: "pt" },
  { name: "Russian", value: "ru" },
  { name: "Swedish", value: "sv" },
  { name: "Urdu", value: "ud" },
  { name: "Chinese", value: "zh" }
]
// export const countries = [
//   { name: "United Arab Emirates", value: "ae" },
//   { name: "Argentina", value: "ar" },
//   { name: "Austria", value: "at" },
//   { name: "Australia", value: "au" },
//   { name: "Belgium", value: "be" },
//   { name: "Bulgaria", value: "bg" },
//   { name: "Brazil", value: "br" },
//   { name: "Canada", value: "ca" },
//   { name: "Switzerland", value: "ch" },
//   { name: "China", value: "cn" },
//   { name: "Colombia", value: "co" },
//   { name: "Cuba", value: "cu" },
//   { name: "Czech Republic", value: "cz" },
//   { name: "Germany", value: "de" },
//   { name: "Egypt", value: "eg" },
//   { name: "France", value: "fr" },
//   { name: "United Kingdom", value: "gb" },
//   { name: "Greece", value: "gr" },
//   { name: "Hong Kong", value: "hk" },
//   { name: "Hungary", value: "hu" },
//   { name: "Indonesia", value: "id" },
//   { name: "Ireland", value: "ie" },
//   { name: "Israel", value: "il" },
//   { name: "India", value: "in" },
//   { name: "Italy", value: "it" },
//   { name: "Japan", value: "jp" },
//   { name: "South Korea", value: "kr" },
//   { name: "Lithuania", value: "lt" },
//   { name: "Latvia", value: "lv" },
//   { name: "Morocco", value: "ma" },
//   { name: "Mexico", value: "mx" },
//   { name: "Malaysia", value: "my" },
//   { name: "Nigeria", value: "ng" },
//   { name: "Netherlands", value: "nl" },
//   { name: "Norway", value: "no" },
//   { name: "New Zealand", value: "nz" },
//   { name: "Philippines", value: "ph" },
//   { name: "Poland", value: "pl" },
//   { name: "Portugal", value: "pt" },
//   { name: "Romania", value: "ro" },
//   { name: "Serbia", value: "rs" },
//   { name: "Russia", value: "ru" },
//   { name: "Saudi Arabia", value: "sa" },
//   { name: "Sweden", value: "se" },
//   { name: "Singapore", value: "sg" },
//   { name: "Slovenia", value: "si" },
//   { name: "Slovakia", value: "sk" },
//   { name: "Thailand", value: "th" },
//   { name: "Turkey", value: "tr" },
//   { name: "Taiwan", value: "tw" },
//   { name: "Ukraine", value: "ua" },
//   { name: "United States", value: "us" },
//   { name: "Venezuela", value: "ve" },
//   { name: "South Africa", value: "za" }
// ]


export const countries = [
  { name: "Afghanistan", value: "af" },
  { name: "Albania", value: "al" },
  { name: "Algeria", value: "dz" },
  { name: "Andorra", value: "ad" },
  { name: "Angola", value: "ao" },
  { name: "Argentina", value: "ar" },
  { name: "Armenia", value: "am" },
  { name: "Australia", value: "au" },
  { name: "Austria", value: "at" },
  { name: "Azerbaijan", value: "az" },
  { name: "Bahamas", value: "bs" },
  { name: "Bahrain", value: "bh" },
  { name: "Bangladesh", value: "bd" },
  { name: "Barbados", value: "bb" },
  { name: "Belarus", value: "by" },
  { name: "Belgium", value: "be" },
  { name: "Belize", value: "bz" },
  { name: "Benin", value: "bj" },
  { name: "Bermuda", value: "bm" },
  { name: "Bhutan", value: "bt" },
  { name: "Bolivia", value: "bo" },
  { name: "Bosnia And Herzegovina", value: "ba" },
  { name: "Botswana", value: "bw" },
  { name: "Brazil", value: "br" },
  { name: "Brunei", value: "bn" },
  { name: "Bulgaria", value: "bg" },
  { name: "Burkina Faso", value: "bf" },
  { name: "Burundi", value: "bi" },
  { name: "Cambodia", value: "kh" },
  { name: "Cameroon", value: "cm" },
  { name: "Canada", value: "ca" },
  { name: "Cape Verde", value: "cv" },
  { name: "Cayman Islands", value: "ky" },
  { name: "Central African Republic", value: "cf" },
  { name: "Chad", value: "td" },
  { name: "Chile", value: "cl" },
  { name: "China", value: "cn" },
  { name: "Colombia", value: "co" },
  { name: "Comoros", value: "km" },
  { name: "Congo", value: "cg" },
  { name: "Cook Islands", value: "ck" },
  { name: "Costa Rica", value: "cr" },
  { name: "Croatia", value: "hr" },
  { name: "Cuba", value: "cu" },
  { name: "Curaçao", value: "cw" },
  { name: "Cyprus", value: "cy" },
  { name: "Czech Republic", value: "cz" },
  { name: "Denmark", value: "dk" },
  { name: "Djibouti", value: "dj" },
  { name: "Dominica", value: "dm" },
  { name: "Dominican Republic", value: "do" },
  { name: "DR Congo", value: "cd" },
  { name: "Ecuador", value: "ec" },
  { name: "Egypt", value: "eg" },
  { name: "El Salvador", value: "sv" },
  { name: "Equatorial Guinea", value: "gq" },
  { name: "Eritrea", value: "er" },
  { name: "Estonia", value: "ee" },
  { name: "Eswatini", value: "sz" },
  { name: "Ethiopia", value: "et" },
  { name: "Fiji", value: "fj" },
  { name: "Finland", value: "fi" },
  { name: "France", value: "fr" },
  { name: "French Polynesia", value: "pf" },
  { name: "Gabon", value: "ga" },
  { name: "Gambia", value: "gm" },
  { name: "Georgia", value: "ge" },
  { name: "Germany", value: "de" },
  { name: "Ghana", value: "gh" },
  { name: "Gibraltar", value: "gi" },
  { name: "Greece", value: "gr" },
  { name: "Grenada", value: "gd" },
  { name: "Guatemala", value: "gt" },
  { name: "Guinea", value: "gn" },
  { name: "Guyana", value: "gy" },
  { name: "Haiti", value: "ht" },
  { name: "Honduras", value: "hn" },
  { name: "Hong Kong", value: "hk" },
  { name: "Hungary", value: "hu" },
  { name: "Iceland", value: "is" },
  { name: "India", value: "in" },
  { name: "Indonesia", value: "id" },
  { name: "Iran", value: "ir" },
  { name: "Iraq", value: "iq" },
  { name: "Ireland", value: "ie" },
  { name: "Israel", value: "il" },
  { name: "Italy", value: "it" },
  { name: "Ivory Coast", value: "ci" },
  { name: "Jamaica", value: "jm" },
  { name: "Japan", value: "jp" },
  { name: "Jersey", value: "je" },
  { name: "Jordan", value: "jo" },
  { name: "Kazakhstan", value: "kz" },
  { name: "Kenya", value: "ke" },
  { name: "Kiribati", value: "ki" },
  { name: "Kosovo", value: "xk" },
  { name: "Kuwait", value: "kw" },
  { name: "Kyrgyzstan", value: "kg" },
  { name: "Laos", value: "la" },
  { name: "Latvia", value: "lv" },
  { name: "Lebanon", value: "lb" },
  { name: "Lesotho", value: "ls" },
  { name: "Liberia", value: "lr" },
  { name: "Libya", value: "ly" },
  { name: "Liechtenstein", value: "li" },
  { name: "Lithuania", value: "lt" },
  { name: "Luxembourg", value: "lu" },
  { name: "Macau", value: "mo" },
  { name: "North Macedonia", value: "mk" },
  { name: "Madagascar", value: "mg" },
  { name: "Malawi", value: "mw" },
  { name: "Malaysia", value: "my" },
  { name: "Maldives", value: "mv" },
  { name: "Mali", value: "ml" },
  { name: "Malta", value: "mt" },
  { name: "Marshall Islands", value: "mh" },
  { name: "Mauritania", value: "mr" },
  { name: "Mauritius", value: "mu" },
  { name: "Mexico", value: "mx" },
  { name: "Micronesia", value: "fm" },
  { name: "Moldova", value: "md" },
  { name: "Monaco", value: "mc" },
  { name: "Mongolia", value: "mn" },
  { name: "Montenegro", value: "me" },
  { name: "Morocco", value: "ma" },
  { name: "Mozambique", value: "mz" },
  { name: "Myanmar", value: "mm" },
  { name: "Namibia", value: "na" },
  { name: "Nauru", value: "nr" },
  { name: "Nepal", value: "np" },
  { name: "Netherlands", value: "nl" },
  { name: "New Caledonia", value: "nc" },
  { name: "New Zealand", value: "nz" },
  { name: "Nicaragua", value: "ni" },
  { name: "Niger", value: "ne" },
  { name: "Nigeria", value: "ng" },
  { name: "North Korea", value: "kp" },
  { name: "Norway", value: "no" },
  { name: "Oman", value: "om" },
  { name: "Pakistan", value: "pk" },
  { name: "Palau", value: "pw" },
  { name: "Palestine", value: "ps" },
  { name: "Panama", value: "pa" },
  { name: "Papua New Guinea", value: "pg" },
  { name: "Paraguay", value: "py" },
  { name: "Peru", value: "pe" },
  { name: "Philippines", value: "ph" },
  { name: "Poland", value: "pl" },
  { name: "Portugal", value: "pt" },
  { name: "Puerto Rico", value: "pr" },
  { name: "Qatar", value: "qa" },
  { name: "Romania", value: "ro" },
  { name: "Russia", value: "ru" },
  { name: "Rwanda", value: "rw" },
  { name: "Saint Lucia", value: "lc" },
  { name: "Saint Martin (Dutch)", value: "sx" },
  { name: "Samoa", value: "ws" },
  { name: "San Marino", value: "sm" },
  { name: "Sao Tome and Principe", value: "st" },
  { name: "Saudi Arabia", value: "sa" },
  { name: "Senegal", value: "sn" },
  { name: "Serbia", value: "rs" },
  { name: "Seychelles", value: "sc" },
  { name: "Sierra Leone", value: "sl" },
  { name: "Singapore", value: "sg" },
  { name: "Slovakia", value: "sk" },
  { name: "Slovenia", value: "si" },
  { name: "Solomon Islands", value: "sb" },
  { name: "Somalia", value: "so" },
  { name: "South Africa", value: "za" },
  { name: "South Korea", value: "kr" },
  { name: "Spain", value: "es" },
  { name: "Sri Lanka", value: "lk" },
  { name: "Sudan", value: "sd" },
  { name: "Suriname", value: "sr" },
  { name: "Sweden", value: "se" },
  { name: "Switzerland", value: "ch" },
  { name: "Syria", value: "sy" },
  { name: "Taiwan", value: "tw" },
  { name: "Tajikistan", value: "tj" },
  { name: "Tanzania", value: "tz" },
  { name: "Thailand", value: "th" },
  { name: "Timor-Leste", value: "tl" },
  { name: "Togo", value: "tg" },
  { name: "Tonga", value: "to" },
  { name: "Trinidad and Tobago", value: "tt" },
  { name: "Tunisia", value: "tn" },
  { name: "Turkey", value: "tr" },
  { name: "Turkmenistan", value: "tm" },
  { name: "Tuvalu", value: "tv" },
  { name: "Uganda", value: "ug" },
  { name: "Ukraine", value: "ua" },
  { name: "United Arab Emirates", value: "ae" },
  { name: "United Kingdom", value: "gb" },
  { name: "United States", value: "us" },
  { name: "Uruguay", value: "uy" },
  { name: "Uzbekistan", value: "uz" },
  { name: "Vanuatu", value: "vu" },
  { name: "Vatican", value: "va" },
  { name: "Venezuela", value: "ve" },
  { name: "Vietnam", value: "vi" },
  { name: "Virgin Islands (British)", value: "vg" },
  { name: "World", value: "wo" },
  { name: "Yemen", value: "ye" },
  { name: "Zambia", value: "zm" },
  { name: "Zimbabwe", value: "zw" }
];
